### ISSUE TITLE
全体の進捗管理・連絡

### ISSUE THREAD

**Issue by ShinoharaTa** [nostr-jp/nostr-idol-project-website#1]
Nostr Idol ProjectサークルのWEBサイトアイデアください

今自分の頭の中にある構想をまずは。

- 同人誌に合わせたデザインを目指す。
  - 同人誌が出るたびに追記されていく感じのページなので、最初の方にNostr Idol ProjectがわかるKeyvisualを置く感じですかね？
  - 2つめの項目がが同人誌の情報
  - 3つ目がNostr Idol Projectとは
  - 4つ目がプロジェクト等？実際のNostrへの誘導などを検討

※当然ながら各コンテンツには文章が必要になるので、このへんはアイデア募ります。

- ロゴ素材なども。
- ラフを頂いて整形してサイトにする。
- CloudflarePages 等にアップしていく予定です。

- HTML、CSSをがーっとコーディングする必要がある
- 見て気づいた点をどんどんGitHub Issueに上げる必要があります。（テスター

4/26ぐらいまでサイトのアイデアなどを募集して構想をまとめたいと思っています。
4/29以降で着手予定です。
完成目標は5/7頃を予定

**Comment by cuconoki** [comment]
レイアウト等のアイデアを膨らませるにあたって、現在公開可能なビジュアル素材をざっと見られるところはありますか？
あれば、それを元に考えられればと思います。

**Comment by ShinoharaTa** [comment]
サイトデザインは、イラスト担当の方々にも相談してみますん

**Comment by mattn** [comment]
現在想定しているウェブサイト(インフラ面)の構成

* 同人誌リリースに合わせて公開しますが基本はサークル用として構築
* ソース管理 GitHub
* GitHub Actions で SSG (Hugo を検討) を使い Cloudflare Pages にデプロイ
* 1枚ぺら (を予定)
* トップにキャッチーな画像 (絵描き班へ依頼)
* サークルの説明と、今回の同人誌に関する説明

**Comment by kawaiirailroads** [comment]
Nostr Idol Projectの概要がわかれば、
それを世界観に合わせて見出しと本文にする……とかなら出来そうです。
謎の技術が何も使われていないHTML5とCSS3でもよろしければコーディングも。

どんなデザインが理想かおききしたいです。
燃えやすいので挙げるのアレなんですが、すとぷり、温泉むすめあたりのサイトデザイン好きです。

**Comment by ShinoharaTa** [comment]
初回からHugoで環境構築したほうが早いか、素のHTML, CSSで組んだほうが早いか脳内シミュレート中

**Comment by mattn** [comment]
* 今後ブログにしたいか
* 何かのデータ(JSON)からコンテンツを生成したいか

あたりが Hugo を使うメリットだと思います。

**Comment by mattn** [comment]
そろそろ動き出した方が良いのかも。

**Comment by ShinoharaTa** [comment]
やります！

**Comment by ShinoharaTa** [comment]
進捗を報告。

- リポジトリにHugo突っ込みました。私のローカルで起動したことは確認しています。
- layouts配下にファイルを追加。
  - ペライチなので、とりあえずデザインチームの方はindex.htmlと404.htmlの実装を進めてください。
  - イベントに向けて現時点では個人間の依存関係を減らすための対応です
- themes/layouts配下で、僕がHugo使った機能の実装をすすめます。
  - お知らせなどの更新機能
  - 過去イベント出展作品などは作品ごとのページに移行

**Comment by ShinoharaTa** [comment]
@kawaiirailroads 
@cuconoki 
デザインなどの話を、こちらのDiscordで行っています。
参加をお願いします。

主にHTML/CSS周りの関係はお願いすると思いますが基本的な部分の技術的な部分の相談窓口は僕が担当します。
https://discord.gg/QgwCNy3M

とりあえず、このプロジェクトをCloneして、Hugoサーバーを起動するところまではまずサポートします
